Fix/65 add zero-address checks
pooltogether/badger-yield-source pull request #6
Opened 2021-06-30 06:54 UTC by kamescg

https://github.com/code-423n4/2021-06-pooltogether-findings/issues/65

2021-07-01 14:48 UTC, PierrickGT commented
The following issue is also related: https://github.com/code-423n4/2021-06-pooltogether-findings/issues/81

2021-07-01 14:50 UTC, PierrickGT requested changes

2021-07-05 21:10 UTC, asselstine commented on contracts/BadgerYieldSource.sol
> +        require(address(badgerAddr) != address(0), "BadgerYieldSource/badgerAddr-not-zero");
Lots of gas $$$ for that.  I don't think it's necessary.

2021-07-05 21:16 UTC, asselstine approved these changes

2021-07-05 22:58 UTC, asselstine approved these changes

2021-07-12 21:30 UTC, PierrickGT approved these changes

2021-07-12 22:08 UTC, asselstine approved these changes

2021-07-12 22:27 UTC, merged